---
- name: reload nginx
  service:
    name: "{{ nginx_service_name }}"
    state: reloaded
  when: not ansible_check_mode

- name: restart nginx
  service:
    name: "{{ nginx_service_name }}"
    state: restarted
  when: not ansible_check_mode